const maindata = {
	"state": 0,
	"message": "OK",
	"totalElements": 0,
	"data": {
		"notices": [{
			"creatTime": "2018-03-14 09:31:33",
			"id": 24,
			"title": "⚽️2018俄罗斯世界杯倒计时92天!竞彩足球开通！提前热身！",
			"sketch": null
		}],
		"types": [{
			"sellStatus": "2",
			"frequencyStatus": "1",
			"id": 19,
			"bannerCopy": "10分开奖超快感",
			"lotteryName": "乐福11选5",
			"lotteryId": "99",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 1,
			"bannerCopy": "奖池近 52亿",
			"lotteryName": "超级大乐透",
			"lotteryId": "35",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 2,
			"bannerCopy": "迎接世界杯中大奖",
			"lotteryName": "竞彩足球",
			"lotteryId": "98",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "1",
			"id": 3,
			"bannerCopy": "10分开奖超快感",
			"lotteryName": "快乐11选5",
			"lotteryId": "97",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 4,
			"bannerCopy": "猜中一场就中奖",
			"lotteryName": "竞足单关",
			"lotteryId": "32",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "2",
			"frequencyStatus": "2",
			"id": 5,
			"bannerCopy": "暂停销售",
			"lotteryName": "足彩六场半全场胜负",
			"lotteryId": "34",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "2",
			"frequencyStatus": "2",
			"id": 6,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球胜平负",
			"lotteryId": "116",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "1",
			"id": 20,
			"bannerCopy": "广告文案",
			"lotteryName": "皖11选5",
			"lotteryId": "96",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "2",
			"frequencyStatus": "2",
			"id": 8,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球混投",
			"lotteryId": "1208",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "2",
			"frequencyStatus": "2",
			"id": 9,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球让球胜平负",
			"lotteryId": "117",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "2",
			"frequencyStatus": "2",
			"id": 10,
			"bannerCopy": "热门赛事竞彩",
			"lotteryName": "足彩四场进球彩",
			"lotteryId": "33",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "2",
			"frequencyStatus": "2",
			"id": 16,
			"bannerCopy": "暂停销售",
			"lotteryName": "test",
			"lotteryId": "33",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 12,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球让球胜平负",
			"lotteryId": "12",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 13,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球让球胜平负",
			"lotteryId": "13",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 14,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球让球胜平负",
			"lotteryId": "14",
			"copyColor": "广告文案"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 15,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球让球胜平负",
			"lotteryId": "120",
			"copyColor": "广告文案"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 11,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球让球胜平负",
			"lotteryId": "11",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "2",
			"frequencyStatus": "2",
			"id": 7,
			"bannerCopy": "暂停销售",
			"lotteryName": "竞彩足球半场胜平负",
			"lotteryId": "127",
			"copyColor": "文案颜色"
		}, {
			"sellStatus": "1",
			"frequencyStatus": "2",
			"id": 22,
			"bannerCopy": "500万大奖等你来拿",
			"lotteryName": "双色球",
			"lotteryId": "40",
			"copyColor": "文案颜色"
		}],
		"banners": [{
			"smallImgUrl": "http://118.31.18.202:8080/reload/public/lottery/banner_zj11x5.png",
			"linkUrl": "99",
			"id": 4,
			"sort": 99,
			"title": "浙江11x5",
			"bigImgUrl": "http://118.31.18.202:8080null"
		}, {
			"smallImgUrl": "http://118.31.18.202:8080/reload/public/lottery/banner_foot.png",
			"linkUrl": "98",
			"id": 2,
			"sort": 98,
			"title": "足球",
			"bigImgUrl": "http://118.31.18.202:8080null"
		}, {
			"smallImgUrl": "http://118.31.18.202:8080/reload/public/lottery/banner_dle.png",
			"linkUrl": "35",
			"id": 1,
			"sort": 35,
			"title": "大乐透",
			"bigImgUrl": "http://118.31.18.202:8080null"
		}, {
			"smallImgUrl": "http://118.31.18.202:8080/reload/public/lottery/banner_ssq.png",
			"linkUrl": "33",
			"id": 3,
			"sort": 33,
			"title": "双色球",
			"bigImgUrl": "http://118.31.18.202:8080null"
		}]
	}
}
export default maindata